#!/bin/sh

basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node.exe" ]; then
  "$basedir/node.exe" "$basedir/tools/ribbit-cli.js" "$@"
else
  node "$basedir/tools/ribbit-cli.js" "$@"
fi
